### ISSUE TITLE
cv2 requirement to be called once

### ISSUE THREAD

**Issue by andreabassi78** [GiorgiaTortora/napari-roi-registration#1]
cv2 is called several times in [here](https://github.com/GiorgiaTortora/napari-roi-registration/blob/bc2ba2409df6a580624c0564db3ef1051ae3bf7d/src/napari_roi_registration/registration_utils.py), instead of having it called once at the beginning. 

When testing, cv2 is called and, not being in the requirements, gives test failure.
I added opencv-python in [the requirements](https://github.com/GiorgiaTortora/napari-roi-registration/blob/bc2ba2409df6a580624c0564db3ef1051ae3bf7d/setup.cfg#L35-L55) but the testing seems not to be able to recognise cv2 anyway. Let's check, it should be a common problem

**Comment by GiorgiaTortora** [comment]
It seems that adding opencv-python in the requirements it's not enough to solve the problem. I'm working on this to find a solution

**Comment by andreabassi78** [comment]
Yes, there seems to be a problem with import cv2 in napari. Something similar to napari  [issue 1026](https://github.com/napari/napari/issues/1026) 
I made fix importing cv2 in the functions that uses it only.
This is not ideal for testing the registration function, but the requirements are now correctly set.
It's worth releasing a new version so that the users get the correct setup.cfg file. 
Can we close the issue?

**Comment by GiorgiaTortora** [comment]
Yes, a new version is now availabe and I'm going to close this issue

**Comment by GiorgiaTortora** [comment]
Yes, a new version is now available and I'm going to close this issue
