### ISSUE TITLE
saving data in a selected folder in process function

### ISSUE THREAD

**Issue by micropolimi** [GiorgiaTortora/napari-roi-registration#3]
When selecting the saving folder one has to select a file. 
It'd be more appropriate to select a folder directly.

Not sure if this can be done using the magicgui directly, but instead of having a file, as a parameter of the process function, it'd be good to have the chosen folder.

**Comment by andreabassi78** [comment]
Saving file is not appropriate, [here](https://github.com/GiorgiaTortora/napari-roi-registration/blob/c538f648237b0aaaca2302ba7354619e20a26c33/src/napari_roi_registration/_widget.py#L458C13-L458C64).

It should be substituted with a saving directory and the saving path should merge the directory with a filename with os.join(directory, filename + '.xlsx')

**Comment by GiorgiaTortora** [comment]
It is now possible to choose the folder where to save the file and also the file name.
